zeobot:
  enabled: true
  features:
    can_comment: true

auto_assign:
  enabled: true
  use_review_groups: false
  use_assignee_groups: false
  add_reviewers: true
  add_assignees: false
  number_of_assignees: 0
  number_of_reviewers: 0
  review_groups:
  assignee_groups:
  reviewers_to_add:
    - TeodorHMX1
    - Teogor
  assignees_to_add:
  skip_keywords:
autodelete_merged_branches:
  enabled: true
  branches_to_exclude:
branch_in_progress:
  enabled: true
contributors_commits_signed:
  enabled: true
  require_for:
    members: false
enforce_branch_merge:
  enabled: true
  branches_to_enforce:
    - master
  give_access_to:
    - TeodorHMX1
    - Teogor
    - ZeoBot[Bot]